<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="agap" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
 <wsdl:message name="helloRequest">
  <wsdl:part name="name" type="xsd:string"/>
 </wsdl:message>
 <wsdl:message name="helloResponse">
  <wsdl:part name="name" type="xsd:string"/>
 </wsdl:message>
 <wsdl:portType name="helloPortType">
  <wsdl:operation name="hello">
   <wsdl:input message="tns:helloRequest"/>
   <wsdl:output message="tns:helloResponse"/>
  </wsdl:operation>
 </wsdl:portType>
 <wsdl:binding name="helloBinding" type="tns:helloPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <wsdl:operation name="hello">
   <soap:operation soapAction="urn:xmethods-delayed-quotes#hello"/>
   <wsdl:input>
    <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
   </wsdl:input>
   <wsdl:output>
    <soap:body use="encoded" namespace="urn:xmethods-delayed-quotes" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
   </wsdl:output>
  </wsdl:operation>
 </wsdl:binding>
 <wsdl:service name="helloService">
  <wsdl:port name="helloPort" binding="helloBinding">
   <soap:address location="http://localhost/testWS/server.php"/>
  </wsdl:port>
 </wsdl:service>
</wsdl:definitions>
